### ISSUE TITLE
请教MSDialog数据问题

### ISSUE THREAD

**Issue by jrcxb** [yangliuy/NeuralResponseRanking#4]
请问MSDialog的数据链接进去没有看到下载的链接呢？

**Comment by yangliuy** [comment]
Hi 你好

请根据 https://ciir.cs.umass.edu/downloads/msdialog/ 这个页面上面的instructions下载数据。Instructions on Getting the Data

**Comment by jrcxb** [comment]
是需要发送邮件到info@ciir.cs.umass.edu吗  一般多久能收到回复呢，谢谢

**Comment by yangliuy** [comment]
是的。应该不会很久，这个具体是我们lab的工作人员处理的，他们验证身份后会发给你一个加密的下载链接。你就可以直接下载了。

**Comment by jrcxb** [comment]
好的哈，链接工作人员已给我发送，谢谢！
